version: '3'

services:
    app:
        build: .
        command: npm run dev
        ports:
        - '3000:3000'
        volumes:
        - .:/code
        - api-deps:/code/node_modules
        environment:
        - NTBA_FIX_319=1
        - MONGO_URI=mongodb+srv://SINNER_LS:97471535In@sinner.54fjy.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
        - TOKEN=1419935389:AAGH1ed0OWppcm5zncEM6xdE7wOLaQfrfwU
        depends_on:
        - mongo
        links:
        - mongo
    mongo:
        image: 'mongo:3.6'
        volumes:
            - mongo-crawler-bot:/data/db
        ports:
            - '27017:27017'

volumes:
    mongo-crawler-bot:
    api-deps:
